let fileList=[
	{
		title:'audio/*',
		desc:'接受所有的声音文件'
	},
	{
		title:'video/*',
		desc:'接受所有的视频文件'
	},
	{
		title:'image/*',
		desc:'接受所有的图像文件'
	},
	{
		title:'*.3gpp',
		desc:'audio/3gpp, video/3gpp'
	},
	{
		title:'*.ac3',
		desc:'audio/ac3'
	},
	{
		title:'*.asf',
		desc:'allpication/vnd.ms-asf'
	},
	{
		title:'*.au',
		desc:'audio/basic'
	},
	{
		title:'*.css',
		desc:'text/css'
	},
	{
		title:'*.csv',
		desc:'text/csv'
	},
	{
		title:'*.doc',
		desc:'application/msword'
	},
	{
		title:'*.dot',
		desc:'application/msword'
	},
	{
		title:'*.dtd',
		desc:'application/xml-dtd'
	},
	{
		title:'*.dwg',
		desc:'image/vnd.dwg'
	},
	{
		title:'*.dxf',
		desc:'image/vnd.dxf'
	},
	{
		title:'*.docx',
		desc:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
	},
	{
		title:'*.dotx',
		desc:'application/vnd.openxmlformats-officedocument.wordprocessingml.template'
	},
	{
		title:'*.gif',
		desc:'image/gif'
	},
	{
		title:'*.htm',
		desc:'text/html'
	},
	{
		title:'*.html',
		desc:'text/html'
	},
	{
		title:'*.jp2',
		desc:'image/jp2'
	},
	{
		title:'*.jpe',
		desc:'image/jpeg'
	},
	{
		title:'*.jpeg',
		desc:'image/jpeg'
	},
	{
		title:'*.jpg',
		desc:'image/jpeg'
	},
	{
		title:'*.js',
		desc:'text/javascript, application/javascript'
	},
	{
		title:'*.json',
		desc:'application/json'
	},
	{
		title:'*.mp2',
		desc:'audio/mpeg, video/mpeg'
	},
	{
		title:'*.mp3',
		desc:'audio/mpeg'
	},
	{
		title:'*.mp4',
		desc:'audio/mp4, video/mp4'
	},
	{
		title:'*.mpeg',
		desc:'video/mpeg'
	},
	{
		title:'*.mpg',
		desc:'video/mpeg'
	},
	{
		title:'*.mpp',
		desc:'application/vnd.ms-project'
	},
	{
		title:'*.ogg',
		desc:'application/ogg, audio/ogg'
	},
	{
		title:'*.pdf',
		desc:'application/pdf'
	},
	{
		title:'*.png',
		desc:'image/png'
	},
	{
		title:'*.pot',
		desc:'application/vnd.ms-powerpoint'
	},
	{
		title:'*.pps',
		desc:'application/vnd.ms-powerpoint'
	},
	{
		title:'*.ppt',
		desc:'application/vnd.ms-powerpoint'
	},
	{
		title:'*.potx',
		desc:'application/vnd.openxmlformats-officedocument.presentationml.template'
	},
	{
		title:'*.ppsx',
		desc:'application/vnd.openxmlformats-officedocument.presentationml.slideshow'
	},
	{
		title:'*.pptx',
		desc:'application/vnd.openxmlformats-officedocument.presentationml.presentation'
	},
	{
		title:'*.rtf',
		desc:'application/rtf, text/rtf'
	},
	{
		title:'*.svf',
		desc:'image/vnd.svf'
	},
	{
		title:'*.sldx',
		desc:'application/vnd.openxmlformats-officedocument.presentationml.slide'
	},
	{
		title:'*.tif',
		desc:'image/tiff'
	},
	{
		title:'*.tiff',
		desc:'image/tiff'
	},
	{
		title:'*.txt',
		desc:'text/plain'
	},
	{
		title:'*.wdb',
		desc:'application/vnd.ms-works'
	},
	{
		title:'*.wps',
		desc:'application/vnd.ms-works'
	},
	{
		title:'*.xhtml',
		desc:'application/xhtml+xml'
	},
	{
		title:'*.xlc',
		desc:'application/vnd.ms-excel'
	},
	{
		title:'*.xlm',
		desc:'application/vnd.ms-excel'
	},
	{
		title:'*.xls',
		desc:'application/vnd.ms-excel'
	},
	{
		title:'*.xlt',
		desc:'application/vnd.ms-excel'
	},
	{
		title:'*.xlw',
		desc:'application/vnd.ms-excel'
	},
	{
		title:'*.xml',
		desc:'application/vnd.ms-excel'
	},
	{
		title:'*.xlsx',
		desc:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
	},
	{
		title:'*.xltx',
		desc:'application/vnd.openxmlformats-officedocument.spreadsheetml.template'
	},
	{
		title:'*.xlsm',
		desc:'application/vnd.ms-excel.addin.macroEnabled.12'
	},
	{
		title:'*.xlsb',
		desc:'application/vnd.ms-excel.sheet.binary.macroEnabled.12'
	},
	{
		title:'*.zip',
		desc:'application/zip'
	},

]

export default fileList