/*创建元素的统一操作 */
import DomTreeEngine from "./domtree.js"
System.requestDomTags=()=>{
	return [
		{
			kind:"常用元素",
			children:[
				{tag:"a",input:true},{tag:"audio"},{tag:"article"},{tag:"button",input:true},{tag:"br"},{tag:"div",input:true},{tag:"dl",input:true},{tag:"dt",input:true},{tag:"dd",input:true},
				{tag:"em",input:true},{tag:"form"},{tag:"h1",input:true},{tag:"h2",input:true},{tag:"h3",input:true},{tag:"h4",input:true},{tag:"h5",input:true},{tag:"h6",input:true},{tag:"header",input:true},
				{tag:"input"},{tag:"img"},{tag:"li",input:true},{tag:"main",input:true},{tag:"nav"},{tag:"ol",input:true},{tag:"option",input:true},{tag:"p",input:true},{tag:"span",input:true},{tag:"select"},{tag:"strong",input:true},
				{tag:"table"},{tag:"th",input:true},{tag:"td",input:true},{tag:"textarea"},{tag:"ul",input:true},{tag:"video"},
				
			]
		},
		{
			kind:"内容分区",
			children:[
				{tag:"address",input:true},
				{tag:"article"},
				{tag:"aside"},
				{tag:"footer",input:true},
				{tag:"header",input:true},
				{tag:"h1",input:true},
				{tag:"h2",input:true},
				{tag:"h3",input:true},
				{tag:"h4",input:true},
				{tag:"h5",input:true},
				{tag:"h6",input:true},
				{tag:"main",input:true},
				{tag:"nav"},
				{tag:"section"},
			]
		},
		{
			kind:"文本内容",
			children:[
				{tag:"blockquote",input:true},
				{tag:"dd",input:true},
				{tag:"div",input:true},
				{tag:"dl",input:true},
				{tag:"dt",input:true},
				{tag:"h6",input:true},
				{tag:"<figcaption>",input:true},
				{tag:"figure",input:true},
				{tag:"hr",input:true},
				{tag:"li",input:true},
				{tag:"menu"},
				{tag:"ol",input:true},
				{tag:"p",input:true},
				{tag:"pre",input:true},
				{tag:"ul",input:true},
			]
		},
		{
			kind:"内敛文本语义",
			children:[
				{tag:"a",input:true},
				{tag:"abbr",input:true},
				{tag:"b",input:true},
				{tag:"bdi",input:true},
				{tag:"bdo",input:true},
				{tag:"cite",input:true},
				{tag:"br",input:true},
				{tag:"code",input:true},
				{tag:"data",input:true},
				{tag:"dfn",input:true},
				{tag:"em",input:true},
				{tag:"i",input:true},
				{tag:"kbd",input:true},
				{tag:"mark",input:true},
				{tag:"q",input:true},
				{tag:"rp",input:true},
				{tag:"rt",input:true},
				{tag:"ruby",input:true},
				{tag:"s",input:true},
				{tag:"samp",input:true},
				{tag:"small",input:true},
				{tag:"span",input:true},
				{tag:"strong",input:true},
				{tag:"sub",input:true},
				{tag:"sup",input:true},
				{tag:"time",input:true},
				{tag:"u",input:true},
				{tag:"var",input:true},
				{tag:"wbr",input:true},
			]
		},{
			kind:"图片和多媒体",
			children:[
				{tag:"area"},
				{tag:"audio"},
				{tag:"img"},
				{tag:"map"},
				{tag:"track"},
				{tag:"canvas"}
			]
		},
		{
			kind:"内嵌内容",
			children:[
				{tag:"embed"},
				{tag:"iframe"},
				{tag:"object"},
				{tag:"picture"},
				{tag:"portal"},
				{tag:"source"},
			]
		},
		{
			kind:"脚本",
			children:[
				{tag:"noscript"},
				{tag:"script"},
			]
		},
		{
			kind:"编辑标识",
			children:[
				{tag:"del",input:true},
				{tag:"ins",input:true},
			]
		},
		{
			kind:"表格内容",
			children:[
				{tag:"caption"},
				{tag:"col",input:true},
				{tag:"colgroup"},
				{tag:"table"},
				{tag:"tbody"},
				{tag:"td",input:true},
				{tag:"tfoot"},
				{tag:"th",input:true},
				{tag:"thead"},
				{tag:"tr",input:true},
			]
		},
		{
			kind:"表单",
			children:[
				{tag:"button",input:true},
				{tag:"detalist"},
				{tag:"fieldset"},
				{tag:"form"},
				{tag:"input"},
				{tag:"label",input:true},
				{tag:"legend",input:true},
				{tag:"meter"},
				{tag:"optgroup"},
				{tag:"option",input:true},
				{tag:"output"},
				{tag:"progress"},
				{tag:"select"},
				{tag:"textarea"},
			]
		},
		{
			kind:"交互元素",
			children:[
				{tag:"details"},
				{tag:"dialog"},
				{tag:"summary"},
			]
		}
	]
}
function init(){
    DomTreeEngine.init()
}
export default{
    name:"CREATE",
    init
}