/*
dom节点数据
除HUB与event的系统事件、剪贴板、回收站对整个项目有效外
所有数据仅对当前页（views）有效 

切换编辑页时重新加载
[
                        {
                        id:"dom1",
                        tag:"div",//group时表示为元素组
                        lock:1,//1锁定，0解锁
                        name:"元素1",
                        parent:null,
                        //condition:null,移入bind中
                        loop:false,
                        input:[],//为组件时才会有,表示传入值
                        event:[],//表示组件中$emit调用的父容器的事件
                        bind:[],//绑定参数，除去v-for，剩余的v-if,v-model等
                        children:["dom2","dom5","demo1"],
                        loopSource:null,
                        area:[10,20,30,40]},
                        {
                            id:"dom2",
                            tag:"div",
                            name:"元素2",
                            parent:"dom1",
                            lock:1,//1锁定，0解锁
                            //condition:null,移入bind中
                            loop:false,
                            input:[],//为组件时才会有,表示传入值
                            event:[],//表示组件中$emit调用的父容器的事件
                            bind:[],//绑定参数，除去v-for，剩余的v-if,v-model等
                            children:[],
                            loopSource:null,
                            area:[10,20,30,40]},
                        {
                            id:"dom3",
                            tag:"div",
                            lock:1,//1锁定，0解锁
                            name:"元素1",
                            parent:null,
                            //condition:null,移入bind中
                            loop:false,
                            input:[],//为组件时才会有,表示传入值
                            event:[],//表示组件中$emit调用的父容器的事件
                            bind:[],//绑定参数，除去v-for，剩余的v-if,v-model等
                            children:["dom4"],
                            loopSource:null,
                            area:[10,20,30,40]},
                            {
                                id:"dom4",
                                tag:"div",
                                name:"元素2",
                                parent:"dom3",
                                lock:1,//1锁定，0解锁
                                //condition:null,移入bind中
                                loop:false,
                                input:[],//为组件时才会有,表示传入值
                                event:[],//表示组件中$emit调用的父容器的事件
                                bind:[],//绑定参数，除去v-for，剩余的v-if,v-model等
                                children:[],
                                loopSource:null,
                                area:[10,20,30,40]},
                            {
                                id:"dom5",
                                tag:"div",
                                name:"元素2",
                                parent:"dom1",
                                lock:1,//1锁定，0解锁
                                //condition:null,移入bind中
                                loop:false,
                                input:[],//为组件时才会有,表示传入值
                                event:[],//表示组件中$emit调用的父容器的事件
                                bind:[],//绑定参数，除去v-for，剩余的v-if,v-model等
                                children:[],
                                loopSource:null,
                                area:[10,20,30,40]},
                                {
                                    id:"demo1",
                                    tag:"demo1",
                                    name:"元素2",
                                    parent:"dom1",
                                    lock:1,//1锁定，0解锁
                                    //condition:null,移入bind中
                                    loop:false,
                                    input:[],//为组件时才会有,表示传入值
                                    event:[],//表示组件中$emit调用的父容器的事件
                                    bind:[],//绑定参数，除去v-for，剩余的v-if,v-model等
                                    children:[],
                                    loopSource:null,
                                    area:[10,20,30,40]}],
									{"dom1":0,"dom2":1,"dom3":2,"dom4":3,"dom5":4,"demo1":5}
*/
import {defineStore} from "pinia"
/*元素的锁定再project.vue中通过在choseGroup中获取是否村存在，存在则为选定 */
export const structStore= defineStore({
    id:"struct",
    state:()=>{
        return{
			System:{//系统数据
				
			},
			PROPERTYPE:{
				
			},//项目属性，包含组件列表等参数
            DOMSTRUCT:{//结构字典
                DEVICE_WEB:{
                    tree:{
						"asjdka2asd":{
							"name":"节点1",
							"tag":"div",
							"status":{
								lock:1,
								'editing':false,
								'editingMan':""
							},
							"propertype":{
								id:"asjdka2asd",	
							},
							"event":{
								
							},
							'condition':{},
							"parent":null, 
							'children':['asjdka2asd_in']
						},
						"asjdka2asd2":{
							"name":"节点2",
							"tag":"div",
							"status":{
								lock:1,
								'editing':false,
								'editingMan':""
							},
							"propertype":{
								id:"asjdka2asd",	
							},
							"event":{
								
							},
							'condition':{},
							"parent":null, 
							'children':[]
						},
						"asjdka2asd_in":{
							"name":"",
							"tag":"div",
							"status":{
								lock:1,
								'editing':false,
								'editingMan':""
							},
							"propertype":{
								id:"asjdka2asd",	
							},
							"event":{
								
							},
							'condition':{},
							"parent":'asjdka2asd',
							'children':["asjdka2asd_in2"]
						},
						"asjdka2asd_in2":{
							"name":"",
							"tag":"div",
							"status":{
								lock:1,
								'editing':false,
								'editingMan':""
							},
							"propertype":{
								id:"asjdka2asd",	
							},
							"event":{
								
							},
							'condition':{},
							"parent":'asjdka2asd_in',
							'children':[]
						}
					},
                    index:['asjdka2asd','asjdka2asd2']//tree树结构为数组存储，index表示各个节点在tree数组中的索引，用于在修改元素id等信息时仍能保证先后次序
                },
                DEVICE_PHONE:{},
                DEVICE_PAD:{}
            },
            STYLESTRUCT:{//样式字典
				__ROOT__:{//根节点样式
					
				},
				"asjdka2asd":{
					class:{},
					style:{
						height:{
							value:"",
							children:{
								value:"200",
								unit:"px"
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						width:{
							value:"",
							children:{
								value:"30",
								unit:"vw"
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						background:{
							value:"",
							children:{
								backgroundColor:{
									value:"red"
								}
							},	
							condition:{
								bindList:null
							}
							
						}
					}
				},
				"asjdka2asd2":{
					class:{},
					style:{
						height:{
							value:"",
							children:{
								value:"200",
								unit:"px"
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						width:{
							value:"",
							children:{
								value:"300",
								unit:"px"
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						background:{
							value:"",
							children:{
								backgroundColor:{
									value:"var(--mainColorBlue2)"
								}
							},
								
							condition:{
								bindList:null
							}
							
						}
					}
				},
				"asjdka2asd_in":{
					class:{},
					style:{
						height:{
							value:"",
							children:{
								unit:"px",
								value:"100"
							},
							condition:{
								bindList:null
							}
						},
						width:{
							value:"",
							children:{
								unit:"px",
								value:"200"
							},
							condition:{
								bindList:null
							}
						},
						background:{
							value:"",
							children:{
								backgroundColor:{
									value:"blue"
								}
							},
								
							condition:{
								bindList:null
							}
							
						}
					}
				},
				"asjdka2asd_in2":{
					class:{},
					style:{
						height:{
							value:"",
							children:{
								unit:"px",
								value:"50"
							},
							condition:{
								bindList:null
							}
						},
						width:{
							value:"",
							children:{
								unit:"px",
								value:"100"
							},
							condition:{
								bindList:null
							}
						},
						background:{
							value:"",
							children:{
								backgroundColor:{
									value:"green"
								}
							},
								
							condition:{
								bindList:null
							}
							
						}
					}
				},
                "dom1":{
                    class:{
                        //"class1":null,//class条件解释，键值为null代表不需要对使用进行条件判断，直接使用class，否则使用:class绑定
                        //"class2":"abc == 123",
						},
                    style:{
						"margin":{
							value:"",
							children:{
								"marginLeft":"",
								"marginTop":"",
								"marginRight":"",
								"marginBottom":"",
							}
						},
						"padding":{
							value:"",
							children:{
								"paddingLeft":"10px",
								"paddingTop":"",
								"paddingRight":"",
								"paddingBottom":"",
							}
						},
						"effect":{
							value:"",
							children:{
								"boxShadow":
									[
									/*{
										"data":{
											X:"10",
											Y:"10",
											B:"5",
											S:"",
											color:"#000"
										},
										type:"外阴影"
									}*/
								],
								"filter":"",
								"backdropFilter":""
								
							}
								
							
						},
                      
						"display":{
						    value:"flex",
							children:{
								"flexDirection":"row",
								"flexWrap":"",
								"alignContent":"",
								"justifyContent":"",
								"alignItems":""
							},
						    condition:null        
						},
						"font":{
							value:"",
							children:{
								"fontStyle": '',
								"fontVariant": '',
								"fontWeight": '',
								"fontSize": '16em',
								"lineHeight": '',
								"fontFamily": '',
								"textDecoration": '',
								"textAlign":'',
								"letterSpacing":'',
								"color":'',
								"textShadow":''
							}
						},
						"borderRadius":{value:""
						,children:{
						    "borderTopLeftRadius":"",
						    "borderTopRightRadius":"",
						    "borderBottomLeftRadius":"",
						    "borderBottomRightRadius":"",
						}},
						"background":{
						    value:"",
						children:{
						    "backgroundColor":"#ffffff",
						    "backgroundPosition":"",
						    "backgroundSize":"",
						    "backgroundRepeat":"",
						    "backgroundOrigin":"",
						    "backgroundClip":"",
						    "backgroundAttachment":"",
						    "backgroundImage":"",
							"backgroundBlendMode":""}},
                        "text-align":{
                            value:"left",
                            condition:null
                        },
                        "white-space":{
                            value:"nowrap",
                            condition:null
                        },
                        "overflow":{
                            value:"hidden",
                            condition:null
                        },
						"text-shadow":{
							value:"3px 3px 5px rgba(255,128,128,1),-3px -3px 5px rgba(255,158,158,1)",
							condition:null
						},
						"font-size":{
							value:"25px",
							condition:null
						},
						"line-height":{
							value:"25px",
							condition:null
						},
						"letter-spacing":{
							value:"5px",
							condition:null
						},
						"font-style":{
							value:"italic",
							condition:null
						},
						'text-decoration':{
							value:'line-through double',
							condition:null
						},
                            "height":{
                                value:"50vh",
								children:{
									value:287,
									unit:"px"
								},
                                /*varSource:null,
                                varData:null,*/
                                condition:null},
                            "width":{
                                value:"800px",
								children:{
									value:800,
									unit:"px"
								},
                                condition:null},
                            }},
                "dom2":{
                    class:{
                        "class1":null,//class条件解释，键值为null代表不需要对使用进行条件判断，直接使用class，否则使用:class绑定
                        "class2":"abc == 123"},
                    style:{
                        "white-space":{
                            value:"nowrap",
                            condition:null
                        },
                        /*"display":{
                            value:"inline-block",
                            condition:null
                        },*/
                        "background-color":{
                            value:"rgba(103,183,103,1)",
                            /*varSource:null,
                            varData:null,*/
                            condition:null},
                            "height":{
                                value:"50%",
                                /*varSource:null,
                                varData:null,*/
                                condition:null},
                            "width":{
                                value:"50px",
                                /*varSource:null,
                                varData:null,*/
                                condition:null},
                            "margin-top":{
                                value:"0",
                                condition:null
                            },
                            "margin-left":{
                                value:"0px",
                                condition:null},}},
                "dom5":{
                    class:{
                        "class1":null,//class条件解释，键值为null代表不需要对使用进行条件判断，直接使用class，否则使用:class绑定
                        "class2":"abc == 123"},
                    style:{
                        "white-space":{
                            value:"nowrap",
                            condition:null
                        },
                        /*"display":{
                            value:"inline-block",
                            condition:null
                        },*/
                        "background-color":{
                            value:"rgba(103,183,103,1)",
                            /*varSource:null,
                            varData:null,*/
                            condition:null},
                            "height":{
                                value:"50px",
                                /*varSource:null,
                                varData:null,*/
                                condition:null},
                            "width":{
                                value:"60px",
                                /*varSource:null,
                                varData:null,*/
                                condition:null},
                            "margin-top":{
                                value:"20%",
                                condition:null
                            },
                            "margin-left":{
                                value:"20%",
                                condition:null},
							"margin":{
								value:"20%",
								children:{
									"marginLeft":"20%",
									"marginTop":"20%",
									"marginRight":"20%",
									"marginBottom":"20%",
								}
							}}},
                    "dom3":{
                    class:{
                        "class1":null,//class条件解释，键值为null代表不需要对使用进行条件判断，直接使用class，否则使用:class绑定
                        "class2":"abc == 123"},
                    style:{
                        "position":{
                            value:"absolute",
                            condition:null
                        },
                        "background-color":{
                            value:"rgba(200,200,150,1)",
                            /*varSource:null,
                            varData:null,*/
                            condition:null},
                            "height":{
                                value:"200px",
                                /*varSource:null,
                                varData:null,*/
                                condition:null},
                            "width":{
                                value:"200px",
                                condition:null},
                            "right":{
                                value:"10%",
                                condition:null},
                            "top":{
                                value:"20%",
                                condition:null},
                            }},
                    "dom4":{
                        class:{
                            "class1":null,//class条件解释，键值为null代表不需要对使用进行条件判断，直接使用class，否则使用:class绑定
                            "class2":"abc == 123"},
                        style:{
                            "background-color":{
                                value:"rgba(103,183,103,1)",
                                /*varSource:null,
                                varData:null,*/
                                condition:null},
                                "height":{
                                    value:"50%",
                                    /*varSource:null,
                                    varData:null,*/
                                    condition:null},
                                "width":{
                                    value:"50%",
                                    /*varSource:null,
                                    varData:null,*/
                                    condition:null},
                                "margin-top":{
                                    value:"20px",
                                    condition:null
                                },
                                "margin-left":{
                                    value:"100px",
                                    condition:null},}},
            },
            ATTRIBUTESTURCT:{//属性字典
                "dom1":[{name:"test",value:"dom",varData:null},{name:"test2",value:"dom&$",varData:"item.name"}]
            },
            DATASETSTURCT:{//数据集字典
                "dom1":[{name:"name",value:"dom&$",varData:"item.name"}]
                /*varData:数据名称 &表示替代+号完成拼接操作，$表示使用变量数据*/
            },
			//全局CSS列表[APP.vue中定义的以及当前编辑组件定义的]
			CLASSLIST:{
				VAR:[],//变量前缀
				APP:{
					//APP.vue定义的
					ROOT:{
						text:{
							'--mainColorColorBg2':'#123456'
						}
					},
					BODY:{
						
					},
					'.class2':{
						type:"class",
						name:".class2",
						text:{},
						data:{},
					}
					//...其余样式
				},
				CURRENT:{
					//当前组件的
					'.class1':{
						type:"class",
						name:".class1",
						text:{},
						data:{},
					},
					'.class4':{
						type:"class",
						name:".class4",
						text:{},
						data:{},
					},
					'.class6':{
						type:"class",
						name:".class6",
						text:{},
						data:{},
					},
					'.class7':{
						type:"class",
						name:".class7",
						text:{},
						data:{},
					}
				}
			},
			VIRTUALSTYLE:{//虚拟节点，用于编辑类/生成器的样式等
				
			},
            VARLIST:{//变量字典
				DATA:{
					"DATA_data1":{
						name:"data1",
					    value:{
							test:"123"
						},
						codeText:`{
							test:"123"
						}`,//用于在value为Object时存储对象
					    text:"",//注释
					    //provide:true//是否开放
					}
				},
				PROPS:{
					"PROPS_data12":{
						name:"data12",
						type:"Object",
						codeText:'',//用于在default为Object类型时存储对象
						default:"test",
						text:""
					},
					"data123":{
						name:"data123",
						type:"Object",
						codeText:'',//用于在default为Object类型时存储对象
						default:"test",
						text:""
					},
				},
				COMPUTED:{
					"COMPUTED_data14":{
						name:"data14",
						reference:"",//参考值
						code:"",
						text:""
					}
				},
				PROVIDE:{
					"data15":{
						name:"data15",
						reference:"",//参考值，由系统自动抛出
						text:""
					}
				},
				INJECT:{
					"data16":{
						name:"data16",
						from:"",
						reference:"",//参考值
						text:""
					}
				},
				WATCH:{
					"data17":{
						name:"data17",
						code:"",
						immediate:false,
						deep:false,
						text:""
					},
					"data128":{
						name:"data128",
						code:"",
						immediate:false,
						deep:false,
						text:""
					}
				}
            },
			METHODS:{//方法列表
				'function1':{
					props:[{name:"event",default:""}],//函数形参
					object:1,//仓库中的函数库全都需要function形式
					async:false,//标记是否异步函数
					varList:[
						{
							name:"var2",//变量名称
							default:"test",//变量缺省值，前缀$时表示是赋值为其他变量
							text:"",//注释
							type:"common",//类型
							display:"test",//真正显示内容
							},//注释
							{
								name:"var3",//变量名称
								default:{'abc':123},//变量缺省值，前缀$时表示是赋值为其他变量
								text:"",
								type:"object",
								display:"Object",//真正显示内容//
								}],
					logic:{
						"for_SJIAJD":{
							ecTitle:"循环1",
							allowdGetIndex:false,//是否允许其他组件获取当前组件的logicIndex数据
							ecExplain:"循环1",
							userDefine:{
								argument:["","",""],
							},
							logic:{
								"for_SJIAJDINNER":{
									ecTitle:"循环1__内",
									ecExplain:"循环1",
									userDefine:{
										argument:["","",""],
									},
									logic:{},
									logicIndexKey:[],
									remote:false
								},
							},
							logicIndexKey:["for_SJIAJDINNER"]//操作逻辑的先后加载顺序对应的键名
								
							
						},

					},//操作逻辑
					logicIndexKey:["for_SJIAJD"]//操作逻辑的先后加载顺序对应的键名
					
				},
				'function2':{
					object:1,//仓库中的函数库全都需要function形式
					props:[{name:"event",default:""}],//函数i形参
					async:false,//标记是否异步函数
					varList:[
						{
							name:"var2",//变量名称
							default:"test",//变量缺省值，前缀$时表示是赋值为其他变量
							text:""},//注释
							{
								name:"var3",//变量名称
								default:{'abc':123},//变量缺省值，前缀$时表示是赋值为其他变量
								text:""}//注释
					],
					logic:{
						"for_SJIAJDLL":{
							ecTitle:"循环123",
							allowdGetIndex:false,//是否允许其他组件获取当前组件的logicIndex数据
							ecExplain:"循环123",
							argument:["","",""],
							logic:{
								"for_SJIAJDINNERLL":{
									ecTitle:"循环1123__内",
									ecExplain:"循环1123",
									userDefine:{
										argument:["","",""],
									},
									logic:{},
									logicIndexKey:[],
									remote:false
								},
							},
							logicIndexKey:["for_SJIAJDINNERLL"]//操作逻辑的先后加载顺序对应的键名
								
							
						},
				
					},//操作逻辑
					logicIndexKey:["for_SJIAJDLL"]//操作逻辑的先后加载顺序对应的键名
					
				}
			},
			Events:{
				"dom1":{
					click:{
						name:"鼠标点击",//事件名称
						argument:['$event'],//传参@clikc="clickEvent($event,a,b,c...)"
						object:0,//0表示function形式，1表示()=>形式
						logic:'function1',//执行部分
					}
				}
				/*
					标签事件或者
				*/
			},
			HUB:{
				Mine:{
					FILES:{//文件素材
						type:"entrance",
						children:{
							
						}
					},
					STYLE:{//样式素材
						type:"entrance",
						children:{
							
						}
					},
					COMPONENTS:{//组件素材
						type:"entrance",
						children:{
							
						}
					}
				},
				Project:{//页面加载时仅加载第一层的数据，各个文件夹，在打开时再加载，并且存储回此处
					FILES:{//文件素材
						type:"entrance",
						children:{
							"IMAGES":{'type':"folder",
							children:{
								'11.jpg':{
									type:"image/jpg",
									data:null,
									children:{}
								},
								'12.jpg':{
									type:"image/jpg",
									data:null,
									children:{}
								},
								'21.png':{
									type:"image/jpg",
									data:null,
									children:{}

							}}},
							
						}
					},
					STYLE:{//样式素材
						type:"entrance",
						children:{
							
						}
					},
					COMPONENTS:{//组件素材
						type:"entrance",
						children:{
							
						}
					}
				}
			},
			//状态管理器
			STATUS:{
				'test2':{
					varSource:"test2",
					position:{//节点位置
						left:0,
						top:0
					},
					varList:[
					{
						id:"testId2",
						varValue:"test2"
					},
					{
						id:"testTwo2",
						varValue:"test2"
					}
				]
				},
				'test':{
					varSource:"test",
					position:{//节点位置
						left:0,
						top:0
					},
					varList:[
					{
						id:'testId',
						varValue:'test'
					},
					{
						id:'testTwo',
						varValue:'test'
					}
				]
				}
			},
			ANIMATION:{
				//交互动画
			
					abcId:{//交互发起的节点ID,
						click:{//触发交互的事件
							node_abcId:{//变化节点，以node开头的表示为html节点，以shape_为开头的则表示为图形,以burst_开头的则表示发散，以swirl_开头的则表示漩涡
								repeatTimes:0,
								frameUnit:{
									blur:'px',
									borderRadius:'%'
								},
								frameTagList:{
									//属性名:帧标记
									'x':'x_frame1_tag',
									'y':'y_frame1_tag',
									'blur':'blur_frame1_tag',
									'backgroundColor':'FRAMETAG1-backgroundColor',
									'borderRadius':'borderRadius_frame1_tag'
								},//帧标记
								nextTagList:{
									//帧修改标记
									/*
									frame1:'frame2',
									frame2:frame3
									*/
								   x_frame1_tag:"x_frame2_tag",
								   x_frame2_tag:"x_frame3_tag",
								   'FRAMETAG1-backgroundColor':'FRAMETAG2-backgroundColor',
								   'borderRadius_frame1_tag':'borderRadius_frame2_tag'
								},
								propertype:{
									parent:"#test",
									// selector for HTMLElement
									el: '#abcId' ,
									// animate translateX from 0 to 200 pixels
									// each delta object can have entire set of tween properties and callbacks,
									x_frame1_tag: { '0':"100",startValue:0,endValue:'100%',duration: 1000, delay: 2000,easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
									x_frame2_tag: { '100':"300",startValue:'100%',endValue:'300%',duration: 1000, delay: 3000, easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
									x_frame3_tag: { '300':"100",startValue:'300%',endValue:'100%',duration: 3000, delay: 4000, easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
									blur_frame1_tag:{'0px':'5',startValue:'0px',endValue:'5px',duration:1000},
									y_frame1_tag: { 0: -20,startValue:0,endValue:-20, duration: 2000, onComplete () { console.log('y property animation complete') } },
									'FRAMETAG1-backgroundColor':{ "#ff0000":"#ff0000",startValue:"#123456",endValue:'#456789',duration:3000},
									'FRAMETAG2-backgroundColor':{ "#FF00FF":"#00FFFF",startValue:"#FF00FF",endValue:'#00FFFF',delay:3000,duration:3000},
									borderRadius_frame1_tag:{0:30,duration:3000,delay:1000,endValue:30,startValue:0},
									borderRadius_frame2_tag:{'30':'100',duration:2000,delay:4000,endValue:100,startValue:'30'}
								}
								//参数列表
							},
							node_nodeId2:{//变化节点，以node开头的表示为html节点，以shape_为开头的则表示为图形,以burst_开头的则表示发散，以swirl_开头的则表示漩涡
								repeatTimes:0,
								frameUnit:{
									blur:'px',
									borderRadius:'%'
								},
								frameTagList:{
									//属性名:帧标记
									'x':'x_frame1_tag',
									'y':'y_frame1_tag',
								},//帧标记
								nextTagList:{
									//帧修改标记
									/*
									frame1:'frame2',
									frame2:frame3
									*/
								},
								propertype:{
									parent:"#test",
									// selector for HTMLElement
									el: '#nodeId2' ,
									// animate translateX from 0 to 200 pixels
									// each delta object can have entire set of tween properties and callbacks,
									x_frame1_tag: { '0':"100%",startValue:0,endValue:'100%',duration: 1000, delay: 2000,easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
									y_frame1_tag: { 0: -20,startValue:0,endValue:-20, duration: 2000, onComplete () { console.log('y property animation complete') } },
									}
								//参数列表
							},
						},
						mousedown:{
							node_nodeId:{
								frameUnit:{},
								frameTagList:{},//帧标记
								nextTagList:{},
								propertype:{}
							}
						}
					},
				testId:{//交互发起的节点ID,
					click:{//触发交互的事件
						node_testId:{//变化节点，以node开头的表示为html节点，以shape_为开头的则表示为图形,以burst_开头的则表示发散，以swirl_开头的则表示漩涡
							repeatTimes:0,
							frameUnit:{
								blur:'px',
								borderRadius:'%'
							},
							frameTagList:{
								//属性名:帧标记
								'x':'x_frame1_tag',
								'y':'y_frame1_tag',
								'blur':'blur_frame1_tag',
								'backgroundColor':'FRAMETAG1-backgroundColor',
								'borderRadius':'borderRadius_frame1_tag'
							},//帧标记
							nextTagList:{
								//帧修改标记
								/*
								frame1:'frame2',
								frame2:frame3
								*/
							   x_frame1_tag:"x_frame2_tag",
							   x_frame2_tag:"x_frame3_tag",
							   'FRAMETAG1-backgroundColor':'FRAMETAG2-backgroundColor',
							   'borderRadius_frame1_tag':'borderRadius_frame2_tag'
							},
							propertype:{
								// selector for HTMLElement
								el: '#testId' ,
								// animate translateX from 0 to 200 pixels
								// each delta object can have entire set of tween properties and callbacks,
								x_frame1_tag: { '0':"100",startValue:0,endValue:'100%',duration: 1000, delay: 2000,easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
								x_frame2_tag: { '100':"300",startValue:'100%',endValue:'300%',duration: 1000, delay: 3000, easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
								x_frame3_tag: { '300':"100",startValue:'300%',endValue:'100%',duration: 3000, delay: 4000, easing: 'cubic.out', onComplete () { console.log('x property animation complete') } },
								blur_frame1_tag:{'0px':'5',startValue:'0px',endValue:'5px',duration:1000},
								y_frame1_tag: { 0: -20,startValue:0,endValue:-20, duration: 2000, onComplete () { console.log('y property animation complete') } },
								'FRAMETAG1-backgroundColor':{ "#ff0000":"#ff0000",startValue:"#123456",endValue:'#456789',duration:3000},
								'FRAMETAG2-backgroundColor':{ "#FF00FF":"#00FFFF",startValue:"#FF00FF",endValue:'#00FFFF',delay:3000,duration:3000},
								borderRadius_frame1_tag:{0:30,duration:3000,delay:1000,endValue:30,startValue:0},
								borderRadius_frame2_tag:{'30':'100',duration:2000,delay:4000,endValue:100,startValue:'30'}
							}
							//参数列表
						}
					},
				},
			},
			CUTBORD:[//剪贴板
				
			],
			RECYCLE:{//回收站
					/*
					'file1':{
						type:"file",//类型
						prePath:"",//原地址，dom节点时为父节点名称
						recycleId:001,//回收站ID，删除的文件将全部存储在一个临时文件夹中，为防止出现不同路径中删除同名文件，以回收ID区分文件，节点则保存在本地Storage中
					}*/
				}
        }
    },
    getters:{},
    actions:{}
})