export default{
				__moduleId__:"$DRAWUI_button",
				__moduleName:"按钮",
				props:{
					"prop1":{
						'name':"入参1",
						default:"按钮",
						nowValue:"",
						type:String,
						inputType:1,
						selectOptions:['入参1','入参2']
					},
				},//传参列表
				__ROOT__:{//根节点数据
					innerContent:'$VAR:prop1',//绑定变量blogTitle
					tag:"button",
					style:{
						"width":{
							value:"",
							children:{
								value:100,
								unit:"px"
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						"height":{
							value:"",
							children:{
								value:30,
								unit:"px"
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						"borderRadius":{
							value:""
							,children:{
						    "borderTopLeftRadius":{
										value:5,
										unit:"px",
										condition:{
											bindList:null,
											default:""
										},
									},
						    "borderTopRightRadius":{
										value:5,
										unit:"px",
										condition:{
											bindList:null,
											default:""
										},
									},
						    "borderBottomLeftRadius":{
										value:5,
										unit:"px",
										condition:{
											bindList:null,
											default:""
										},
									},
						    "borderBottomRightRadius":{
										value:5,
										unit:"px",
										condition:{
											bindList:null,
											default:""
										},
									},
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						"background":{
						    value:"",
							children:{
								"backgroundColor":
								{
									value:"#3662ec",
									conditon:{
										bindList:null,
										default:""
									}
								},
								"backgroundPosition":[
								],
								"backgroundSize":[],
								"backgroundRepeat":{
									value:"",
									conditon:{
										bindList:null,
										default:""
									}
								},
								"backgroundOrigin":[],
								"backgroundClip":[],
								"backgroundAttachment":[],
								"backgroundImage":[],
								"backgroundBlendMode":[]
								},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						},
						"font":{
							value:"",
							children:{
								"fontStyle":{
										value:"",
										unit:"",
										condition:{
											bindList:null,
											default:""
										},
									},
								"fontVariant":{
										value:"",
										unit:"",
										condition:{
											bindList:null,
											default:""
										},
									},
								"fontWeight":{
										value:"normal",
										unit:"",
										condition:{
											bindList:null,
											default:""
										},
									},
								"fontSize":{value:""},
								"lineHeight":{
										value:100,
										unit:"%",
										condition:{
											bindList:null,
											default:""
										},
									},
								"fontFamily":{
										value:"",
										unit:"",
										condition:{
											bindList:null,
											default:""
										},
									},
								"textDecoration":{value:""},
								"textAlign":{
										value:"",
										unit:"",
										condition:{
											bindList:null,
											default:""
										},
									},
								"letterSpacing":{
										value:"",
										unit:"",
										condition:{
											bindList:null,
											default:""
										},
									},
								"color":{value:"#ffffff"},
								"textShadow":{
										value:"",
										unit:"",
										condition:{
											bindList:null,
											default:""
										},
									},
							},
							group:false,
							condition:{
								bindList:null,
								default:""
							}
						 },
					},
					class:{}
				},
				//以下为子节点的数据
				DOMSTRUCT:{//结构字典
					DEVICE_WEB:{
						tree:{
							
						},
						index:[]//tree树结构为数组存储，index表示各个节点在tree数组中的索引，用于在修改元素id等信息时仍能保证先后次序
					},
					DEVICE_PHONE:{},
					DEVICE_PAD:{}
				},
				STYLESTRUCT:{
					__ROOT__:{//根节点样式
						
					},
					//样式字典
					
				},
				ATTRIBUTESTURCT:{//属性字典
				},
				DATASETSTURCT:{//数据集字典
					/*varData:数据名称 &表示替代+号完成拼接操作，$表示使用变量数据*/
				},
				//以上为子节点数据
				VARLIST:{//组件变量字典
				},
				CLASSLIST:{},
				METHODS:{//方法列表
				},
				Events:{
				},
		}	