export default{
	__moduleId__:"$DRAWUI_flex",
	__moduleName__:"弹性布局",
	props:{
		"prop1":{
			'name':"入参1",
			default:"默认取值",
			nowValue:"",
			type:String,
			inputType:1,
			selectOptions:['入参1','入参2']
		},
		"prop2":{
			'name':"入参2",
			default:false,
			nowValue:"",
			type:Boolean,
			inputType:2
		},
		"prop3":{
			'name':"入参3",
			default:0,
			nowValue:0,
			type:String,
			inputType:3,
			checkRadios:['取值1','取值2','取值3']
		},
		"prop4":{
			'name':"入参4",
			default:[false,false,false],
			nowValue:[false,false,false],
			type:Array,
			inputType:4,
			checkRadios:['取值1','取值2','取值3']
		},
		"prop5":{
			name:"入参5",
			default:"默认参数",
			nowValue:'',
			type:String,
			inputType:5,
			customize:"testOpen"
		}
	},
	__ROOT__:{
		innerContent:'',//绑定变量blogTitle
		style:{
			"width":{
				value:"",
				children:{
					value:100,
					unit:"px"
				},
				group:false,
				condition:{
					bindList:null,
					default:""
				}
			},
			"height":{
				value:"",
				children:{
					value:30,
					unit:"px"
				},
				group:false,
				condition:{
					bindList:null,
					default:""
				}
			},
			
		},
		class:{},
		content:{}
	},
	DOMSTRUCT:{//结构字典
		DEVICE_WEB:{
			tree:{
				'p1':{
					"name":"",
					"tag":"p",
					innerContent:'$VAR:prop1',
					"status":{
						lock:1,
						'editing':false,
						'editingMan':""
					},
					"propertype":{
						id:"asjdka2asd",	
					},
					"event":{
						
					},
					'condition':{},
					"parent":null, 
					'children':[]
				},
				'$NODE:asdasda':{
					"name":"按钮123",
					"status":{
						lock:1,
						'editing':false,
						'editingMan':""
					},
					'innerContent':'',
					"propertype":{
						id:'asdasda',	
					},
					"event":{
					},
					'condition':{},
					"parent":null,
					__modulePath__:'$DRAWUI_button',
					props:{
						"prop1":"测试按钮"
					}
				}
			},
			index:['p1','$NODE:asdasda']//tree树结构为数组存储，index表示各个节点在tree数组中的索引，用于在修改元素id等信息时仍能保证先后次序
		},
		DEVICE_PHONE:{},
		DEVICE_PAD:{}
	},
	STYLESTRUCT:{
		__ROOT__:{//根节点样式
			
		},
		//样式字典
		p1:{
			style:{},
			class:{},
		},
		"$NODE:asdasda":{
			style:{},
			class:{}
		}
	},
	ATTRIBUTESTURCT:{//属性字典
	},
	DATASETSTURCT:{//数据集字典
		/*varData:数据名称 &表示替代+号完成拼接操作，$表示使用变量数据*/
	},
	//以上为子节点数据
	VARLIST:{//组件变量字典
	},
	CLASSLIST:{},
	METHODS:{//方法列表
	},
	Events:{
	},
}